name: Update Time

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute

jobs:
  update_time:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Python Script
      run: python3 runtime.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update time [skip ci]"
        git push
